### ISSUE TITLE
Feature/Navbar-Active-Tab-Highlight

### ISSUE THREAD

**Issue by Mrigank118** [Mrigank118/Readbee#1]
### Issue Title
Add Active Tab Highlight in Navbar using Tailwind CSS and TypeScript

### Issue Description
**Description:**
Implement a feature to highlight the active tab in the navbar using Tailwind CSS for styling and TypeScript for type safety. When a user is on a specific tab, the corresponding navbar item should have a colored hover effect to indicate the current page.

**Requirements:**

- Track the currently active tab using React state with TypeScript.
- Apply a specific Tailwind CSS class to the active navbar item.
- Ensure the active tab has a distinct hover color different from other tabs.

**Acceptance Criteria:**

- The active tab should have a colored hover effect.
- The hover effect should be applied only to the active tab.
- The feature should be tested for responsiveness and cross-browser compatibility.

**Implementation Details:**

- **React State Management:** Use React's `useState` hook with TypeScript to manage the active tab state.
- **Tailwind CSS:** Apply Tailwind CSS classes to style the active tab and its hover effect.
- **TypeScript:** Ensure type safety throughout the implementation.

**Additional Information:**

- The implementation should ensure the design is consistent with the overall UI/UX of the application.
- Provide any design mockups or references if available.

**Comment by jainritikaa** [comment]
I can solve the issue **"Add Active Tab Highlight in Navbar using Tailwind CSS and TypeScript"**. I have experience with both Tailwind CSS and TypeScript.

### Solution Outline:
1. **State Management**: Use `useState` with TypeScript to track the active tab.
2. **Styling**: Apply Tailwind CSS classes for the active tab and its distinct hover effect.
3. **Responsiveness**: Ensure the feature is responsive and cross-browser compatible.

I look forward to contributing to your project.

**Comment by Mrigank118** [comment]
Thank you for offering to solve the issue "Add Active Tab Highlight in Navbar using Tailwind CSS and TypeScript". Your solution outline looks great. The issue is now assigned to you. Please proceed with the implementation and feel free to reach out if you have any questions.
